name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build apk
      run: ./gradlew assembleDebug

    - name: Build artifacts
      uses: actions/upload-artifact@v4
      with:
        path: build/outputs/apk/debug/*.apk
        retention-days: 30
